name: Test and Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_simplemath.py
        env:
          CI: true

      - name: Check test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          else
            echo "Tests passed"